### ISSUE TITLE
critical error

### ISSUE THREAD

**Issue by Just-A-Programer** [sfybb/Factorio-Codex#6]
while loading a save this error appears 
![Capture](https://user-images.githubusercontent.com/88325989/235843202-7fe3619f-13f1-44a7-81a2-28b68e33a26d.PNG)

i'm playing on 1.1.80 with some mod

**Comment by sfybb** [comment]
I must say this is a strange error. It basically says you are missing a file in the mod.
But this is impossible since I checked and this file is included.
So I must ask:
1. Which version of facorio codex are you using?
2. Can you just send me the mod file so I can check if something got messed up?

**Comment by Just-A-Programer** [comment]
> I must say this is a strange error. It basically says you are missing a file in the mod. But this is impossible since I checked and this file is included. So I must ask:
> 
> 1. Which version of facorio codex are you using?
> 2. Can you just send me the mod file so I can check if something got messed up?


[factorio-codex.zip](https://github.com/sfybb/Factorio-Codex/files/11466351/factorio-codex.zip)

I'm on 1.1.80

**Comment by sfybb** [comment]
You seem to have pressed on "Donload Zip" button for the source code.
![image](https://github.com/sfybb/Factorio-Codex/assets/129160899/e9646a91-abe8-44cf-be51-3d77c1485664)

But in order to use this mod in factorio you have to either download the release `factorio-codex_0.0.20.zip` from [Releases](https://github.com/sfybb/Factorio-Codex/releases) or go trough the factorio mod portal.
